---
version: "2.1"
services:
  folding-at-home:
    build: ./
    container_name: folding-at-home
    environment:
      - FAH_USER=ffissore
      - FAH_TEAM=0
      - FAH_ENABLE_GPU=false
      - FAH_ENABLE_SMP=true
    ports:
      - 7396:7396
      - 36330:36330
    volumes:
      - "fah-data:/fah-data"
      - "fah-cores:/fah-cores"
volumes:
  fah-data:
  fah-cores:
